name: stale

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'skyclouds2001/springboot-template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This pr is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          days-before-stale: 30
          days-before-close: 5
  labeler-size:
      if: github.repository == 'skyclouds2001/springboot-template-sky'
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
          - uses: codelytv/pr-size-labeler@v1
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                github_api_url: https://api.github.com
                xs_label: size/xs
                xs_max_size: 10
                s_label: size/s
                s_max_size: 100
                m_label: size/m
                m_max_size: 500
                l_label: size/l
                l_max_size: 1000
                xl_label: size/xl
                fail_if_xl: false
                message_if_xl: ''
                files_to_ignore: 'package-lock.json *.lock'
